package com.tecnoscimmia.nine.model

/*
 * This file defines the MatchClass, this class contains all the data needed for a match
 */

class Match
{
	private var secretKey: 		String = ""					// Permutation of symbols generated by the game
	private var differences:	String = ""
	private var isPaused:		Boolean = false

	private var attemptsNum:	UInt = 0u					// Total Number of attempts


	// Generates a new secret key using the given symbol set
	fun generatePermutation(symbolSet: String)
	{}


	// Checks
	fun evaluate(userKey: String)
	{}
}